### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by BazZziliuS** [ooliver1/mafic#117]
### Summary

Error during import

### Reproduction Steps

import mafic

### Minimal Reproducible Code

```Python
import mafic
```

### Expected Results

import mafic

### Actual Results

No module named 'pkg_resources'

ModuleNotFoundError: No module named 'pkg_resources'

### Lavalink Information

 Version:        4.0.5

### System Information

```py
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\BazZziliuS\AppData\Local\pypoetry\Cache\virtualenvs\centurybot-7puqhXE1-py3.12\Lib\site-packages\mafic\__init__.py", line 10, in <module>
    from . import __libraries
  File "C:\Users\BazZziliuS\AppData\Local\pypoetry\Cache\virtualenvs\centurybot-7puqhXE1-py3.12\Lib\site-packages\mafic\__libraries.py", line 9, in <module>
    from pkg_resources import (
ModuleNotFoundError: No module named 'pkg_resources'
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Python 3.12

**Comment by ItsNotAlexy** [comment]
You would need to install setup tools.

Via command prompt/terminal:
`pip install setuptools`

**Comment by ItsNotAlexy** [comment]
Refer to this stackoverflow forum: https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
